### PR TITLE
Make the maximum number of connection attempts configurable

### PR DESCRIPTION
**Pull request by adaminglehart**
Hello! Thank you so much for your library. It would be useful for us to be able to configure the max connection attempts before timing out, so I thought I'd put a PR up and see if you're willing to merge it in. I'm not a Rust expert so I'm open to any feedback, but would love to be able to include this in your library rather than maintaining our own fork if possible

### CODE REVIEW

**Comment by wei-rong-1** [comment]
@adaminglehart Thank you for your contribution.
Suppose we want to support configuring the max connection attempts. The better way is to add a set function like `setMaxConnectionAttempts(value: number)` instead of passing the attempts as a new parameter of the `connect` function.
Can you update your PR accordingly?

**Comment by adaminglehart** [comment]
Done! Do you want me to use this set function style in the rust code as well, or are you ok with having it as a parameter in there?

**Comment by wei-rong-1** [comment]
> Done! Do you want me to use this set function style in the rust code as well, or are you ok with having it as a parameter in there?

Yes, both, please.

**Comment by adaminglehart** [comment]
Updated that as well! Please let me know if you have any other feedback

Is there a good way for me to test this? I'm on a Mac so I don't think I'm able to run the tests on my machine, not sure if you have some CI set up?

**Comment by adaminglehart** [comment]
@wei-rong-1 thank you for getting this merged! Whenever possible do you mind doing a new npm release?

**Comment by wei-rong-1** [comment]
@adaminglehart Sure, a new version has been released.

**Pull request merged**
